stages:
  - build
  - sync

variables:
  GO_VERSION: "1.21"
  CGO_ENABLED: "0"

# Build stage
build:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - mkdir -p build
    - make build-all
    - ls -la build/

# GitHub sync stage
github-sync:
  stage: sync
  image: alpine:latest
  variables:
    GIT_STRATEGY: clone
  script:
    - apk add --no-cache git
    - git remote add github https://${GITHUB_TOKEN}@github.com/cploutarchou/swarmforge.git
    - git push github HEAD:main --force
    - git push github --tags --force
  only:
    - main
    - tags
  dependencies: []
