name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  # the workflow can contain other jobs, such as linting, testing, etc.
  release:
    runs-on: ubuntu-latest
    steps:
      # run git checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # setup go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      # Create tag if manually triggered
      - name: Create tag if manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      # run goreleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
          distribution: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
